"""updates

Revision ID: 012dff75f08d
Revises: 3a2a4b21312f
Create Date: 2023-08-25 11:37:28.030102

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "012dff75f08d"
down_revision = "3a2a4b21312f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
