"""updates

Revision ID: 2695dcabd686
Revises: e2f0bf3c350b
Create Date: 2023-08-22 18:45:05.226676

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "2695dcabd686"
down_revision = "e2f0bf3c350b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("webhooks", "signature", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("webhooks", "s3_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "webhooks",
        sa.Column("s3_url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.alter_column("webhooks", "signature", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
