"""updates

Revision ID: 2b2b12a11e19
Revises: 39c4ed9e514a
Create Date: 2023-08-29 22:25:26.018920

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "2b2b12a11e19"
down_revision = "39c4ed9e514a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
