"""updates

Revision ID: 39c4ed9e514a
Revises: 66e8013573db
Create Date: 2023-08-29 19:45:41.930862

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "39c4ed9e514a"
down_revision = "66e8013573db"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assignments",
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "assignments",
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "assignments",
        sa.Column("status", sa.String(), server_default="created", nullable=False),
    )
    op.drop_column("assignments", "finished_at")
    op.drop_column("assignments", "closes_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assignments",
        sa.Column(
            "closes_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "assignments",
        sa.Column(
            "finished_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("assignments", "status")
    op.drop_column("assignments", "completed_at")
    op.drop_column("assignments", "expires_at")
    # ### end Alembic commands ###
