"""updates

Revision ID: 3a2a4b21312f
Revises: a671359903f0
Create Date: 2023-08-25 11:28:41.440939

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "3a2a4b21312f"
down_revision = "a671359903f0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("wallet_id", sa.String(), nullable=False),
        sa.Column("cvat_username", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("wallet_id"),
    )
    op.create_index(
        op.f("ix_users_cvat_username"), "users", ["cvat_username"], unique=True
    )
    op.create_index(op.f("ix_users_wallet_id"), "users", ["wallet_id"], unique=False)
    op.create_table(
        "assignments",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("closes_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_wallet_id", sa.String(), nullable=False),
        sa.Column("cvat_job_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["cvat_job_id"], ["jobs.cvat_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_wallet_id"], ["users.wallet_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assignments_id"), "assignments", ["id"], unique=False)
    op.drop_index("ix_jobs_assignee", table_name="jobs")
    op.drop_column("jobs", "assignee")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs",
        sa.Column(
            "assignee", sa.VARCHAR(length=42), autoincrement=False, nullable=True
        ),
    )
    op.create_index("ix_jobs_assignee", "jobs", ["assignee"], unique=False)
    op.drop_index(op.f("ix_assignments_id"), table_name="assignments")
    op.drop_table("assignments")
    op.drop_index(op.f("ix_users_wallet_id"), table_name="users")
    op.drop_index(op.f("ix_users_cvat_username"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
