"""updates

Revision ID: 56485c70d82a
Revises: 012dff75f08d
Create Date: 2023-08-25 12:21:19.488854

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "56485c70d82a"
down_revision = "012dff75f08d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "last_processed_webhook_delivery_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "last_processed_webhook_delivery_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
