"""add_webhook_data

Revision ID: 5ceab67a6637
Revises: 7e513fd5b004
Create Date: 2023-08-16 17:51:19.652528

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '5ceab67a6637'
down_revision = '7e513fd5b004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('last_processed_webhook_delivery_id', sa.Integer(), nullable=True))
    op.add_column('webhooks', sa.Column('event_type', sa.String(), nullable=False))
    op.add_column('webhooks', sa.Column('event_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhooks', 'event_data')
    op.drop_column('webhooks', 'event_type')
    op.drop_column('projects', 'last_processed_webhook_delivery_id')
    # ### end Alembic commands ###
