"""updates

Revision ID: 66e8013573db
Revises: 6859587a3039
Create Date: 2023-08-29 15:59:27.169970

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "66e8013573db"
down_revision = "6859587a3039"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("cvat_webhook_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "cvat_webhook_id")
    # ### end Alembic commands ###
