"""updates

Revision ID: 6859587a3039
Revises: 825dc9ed9bdb
Create Date: 2023-08-25 18:27:15.016912

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "6859587a3039"
down_revision = "825dc9ed9bdb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("cvat_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_users_cvat_id"), "users", ["cvat_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_cvat_id"), table_name="users")
    op.drop_column("users", "cvat_id")
    # ### end Alembic commands ###
