"""updates

Revision ID: 825dc9ed9bdb
Revises: 88bc42240f44
Create Date: 2023-08-25 18:11:23.649490

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "825dc9ed9bdb"
down_revision = "88bc42240f44"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("cvat_email", sa.String(), nullable=True))
    op.drop_index("ix_users_cvat_username", table_name="users")
    op.create_index(op.f("ix_users_cvat_email"), "users", ["cvat_email"], unique=True)
    op.drop_column("users", "cvat_username")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("cvat_username", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_users_cvat_email"), table_name="users")
    op.create_index("ix_users_cvat_username", "users", ["cvat_username"], unique=False)
    op.drop_column("users", "cvat_email")
    # ### end Alembic commands ###
