"""updates

Revision ID: 88bc42240f44
Revises: 56485c70d82a
Create Date: 2023-08-25 17:49:03.435320

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "88bc42240f44"
down_revision = "56485c70d82a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assignments",
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assignments", "finished_at")
    # ### end Alembic commands ###
