"""updates

Revision ID: a671359903f0
Revises: 2695dcabd686
Create Date: 2023-08-24 18:56:15.363701

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "a671359903f0"
down_revision = "2695dcabd686"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_escrow_address_type_uc", "webhooks", type_="unique")
    op.create_unique_constraint(
        "_escrow_address_type_uc", "webhooks", ["escrow_address", "type", "event_type"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_escrow_address_type_uc", "webhooks", type_="unique")
    op.create_unique_constraint(
        "_escrow_address_type_uc", "webhooks", ["escrow_address", "type"]
    )
    # ### end Alembic commands ###
