"""update_relations

Revision ID: e2f0bf3c350b
Revises: f7ac8738a261
Create Date: 2023-08-17 17:24:02.438906

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "e2f0bf3c350b"
down_revision = "f7ac8738a261"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
