"""add images tracking

Revision ID: f26979d8162b
Revises: 9a7dfe7494c2
Create Date: 2023-09-13 16:55:27.251825

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "f26979d8162b"
down_revision = "9a7dfe7494c2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "images",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("cvat_project_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cvat_project_id"], ["projects.cvat_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cvat_project_id", "filename", name="_project_filename_uc"),
    )
    op.create_index(op.f("ix_images_id"), "images", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_images_id"), table_name="images")
    op.drop_table("images")
    # ### end Alembic commands ###
