"""updates

Revision ID: f7ac8738a261
Revises: 5ceab67a6637
Create Date: 2023-08-17 17:03:01.188862

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "f7ac8738a261"
down_revision = "5ceab67a6637"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_uploads",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.cvat_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_data_uploads_id"), "data_uploads", ["id"], unique=False)
    op.create_index(
        op.f("ix_data_uploads_task_id"), "data_uploads", ["task_id"], unique=True
    )
    op.add_column("webhooks", sa.Column("direction", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("webhooks", "direction")
    op.drop_index(op.f("ix_data_uploads_task_id"), table_name="data_uploads")
    op.drop_index(op.f("ix_data_uploads_id"), table_name="data_uploads")
    op.drop_table("data_uploads")
    # ### end Alembic commands ###
